"""empty message

Revision ID: d7a67c7f2c76
Revises: 
Create Date: 2018-01-17 23:57:09.810925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a67c7f2c76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('rsvp', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('rsvp', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('date_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_modified')
    op.drop_column('users', 'date_created')
    op.drop_column('rsvp', 'date_modified')
    op.drop_column('rsvp', 'date_created')
    op.drop_column('event', 'date_modified')
    op.drop_column('event', 'date_created')
    # ### end Alembic commands ###
